version: "3.9"

services:
  fastchat-controller:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastchat:latest
    ports:
      - "21001:21001"
    entrypoint:
      [
        "python3",
        "-m",
        "fastchat.serve.controller",
        "--host",
        "0.0.0.0",
        "--port",
        "21001"
      ]
  fastchat-model-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - huggingface:/root/.cache/huggingface
      - $PWD/vicuna-13b:/models/vicuna-13b
    environment:
      FASTCHAT_CONTROLLER_URL: http://fastchat-controller:21001
    image: fastchat:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [ gpu ]
    entrypoint:
      [
        "python3",
        "-m",
        "fastchat.serve.model_worker",
        "--model-name",
        'text-embedding-ada-002',
        "--model-path",
        "/models/vicuna-13b",
        "--worker-address",
        "http://fastchat-model-worker:21002",
        "--controller-address",
        "http://fastchat-controller:21001",
        "--host",
        "0.0.0.0",
        "--port",
        "21002",
        "--num-gpus",
        "4"
      ]

  fastchat-api-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FASTCHAT_CONTROLLER_URL: http://fastchat-controller:21001
    image: fastchat:latest
    ports:
      - "8000:8000"
    entrypoint:
      [
        "python3",
        "-m",
        "fastchat.serve.openai_api_server",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--controller-address",
        "http://fastchat-controller:21001"
      ]
    labels:
      - traefik.enable=true
      - traefik.http.routers.dev-app-http.rule=Host(`llm.thoughtstarter.ai`)
      - traefik.http.routers.dev-app-http.tls=true
      - traefik.http.routers.dev-app-http.tls.certresolver=letsencrypt
  vector-fast-api:
    build:
      context: /home/ubuntu/vector-fast-api
      dockerfile: Dockerfile.api
    env_file:
      - /home/ubuntu/vector-fast-api/.env
    environment:
      # - PG_HOST=pgcat
      - LOGGER_NAME=gunicorn.error
    ports:
      - 2005:2005
    labels:
      - traefik.enable=true
      - traefik.http.routers.vector-app-http.rule=Host(`llm-vector.thoughtstarter.ai`)
      - traefik.http.routers.vector-app-http.tls=true
      - traefik.http.routers.vector-app-http.tls.certresolver=letsencrypt

  traefik:
    image: traefik:v2.3
    container_name: traefik
    command:
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - traefik-letsencrypt-v2:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/services/traefik/traefik.toml:/etc/traefik/traefik.toml
volumes:
  huggingface:
  traefik-letsencrypt-v2:
